export interface ModuleSetupOptions {
  extractorType: string;
  dbSettingKey: string;
  autoInjectTenantId: boolean;
  sharedModels: string[];
  tenantFormat?: string;
  customRegex?: string;
}

export function generateModuleSetup(options: ModuleSetupOptions): string {
  // Determine which extractor class (if any) needs to be imported
  const extractorImportMap: Record<string, string> = {
    'Subdomain (tenant1.app.com)': 'SubdomainTenantExtractor',
    'JWT Claim': 'JwtClaimTenantExtractor',
    'Path Parameter': 'PathTenantExtractor',
  };
  const extractorClass = extractorImportMap[options.extractorType];

  // Prisma extension is always needed for RLS — set_config() must run before every query
  const hasExtensionOptions =
    options.autoInjectTenantId ||
    options.sharedModels.length > 0 ||
    options.dbSettingKey !== 'app.current_tenant';

  const lines: string[] = [
    '// Generated by @nestarc/tenancy CLI',
    '// Add to your AppModule imports array.',
    '',
  ];

  // Build the import from @nestarc/tenancy
  const namedImports: string[] = ['TenancyModule'];
  if (extractorClass) {
    namedImports.push(extractorClass);
  }
  if (options.extractorType === 'Composite') {
    if (!namedImports.includes('CompositeTenantExtractor')) {
      namedImports.push('CompositeTenantExtractor');
      namedImports.push('HeaderTenantExtractor');
    }
  }
  namedImports.push('createPrismaTenancyExtension');
  lines.push(`import { ${namedImports.join(', ')} } from '@nestarc/tenancy';`);
  lines.push('');

  lines.push('// In your @Module({ imports: [...] })', 'TenancyModule.forRoot({');

  switch (options.extractorType) {
    case 'Subdomain (tenant1.app.com)':
      lines.push('  tenantExtractor: new SubdomainTenantExtractor(),');
      break;
    case 'JWT Claim':
      lines.push("  // WARNING: JWT signature must be verified BEFORE tenancy middleware.");
      lines.push("  // Add express-jwt or similar middleware BEFORE TenancyModule.");
      lines.push(
        "  tenantExtractor: new JwtClaimTenantExtractor({ claimKey: 'tenant_id' }),",
      );
      break;
    case 'Path Parameter':
      lines.push(
        "  tenantExtractor: new PathTenantExtractor({ pattern: '/api/tenants/:tenantId', paramName: 'tenantId' }),",
      );
      break;
    case 'Composite':
      lines.push("  tenantExtractor: new CompositeTenantExtractor([");
      lines.push("    new HeaderTenantExtractor('X-Tenant-Id'),");
      lines.push("    // Add more extractors here");
      lines.push("  ]),");
      break;
    default:
      lines.push("  tenantExtractor: 'X-Tenant-Id',");
  }

  if (options.tenantFormat === 'Custom' && options.customRegex) {
    // Use new RegExp() instead of /.../ literal to safely handle regex with '/'
    const escaped = options.customRegex.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
    lines.push(`  validateTenantId: (id) => new RegExp('${escaped}').test(id),`);
  }

  if (options.dbSettingKey !== 'app.current_tenant') {
    lines.push(`  dbSettingKey: '${options.dbSettingKey}',`);
  }

  lines.push('})');

  lines.push('');
  lines.push('// Prisma extension — required for RLS to work:');
  lines.push('// const prisma = new PrismaClient().$extends(');
  if (hasExtensionOptions) {
    lines.push('//   createPrismaTenancyExtension(tenancyService, {');
    if (options.autoInjectTenantId) {
      lines.push('//     autoInjectTenantId: true,');
    }
    if (options.sharedModels.length > 0) {
      lines.push(
        `//     sharedModels: [${options.sharedModels.map((m) => `'${m}'`).join(', ')}],`,
      );
    }
    if (options.dbSettingKey !== 'app.current_tenant') {
      lines.push(`//     dbSettingKey: '${options.dbSettingKey}',`);
    }
    lines.push('//   })');
  } else {
    lines.push('//   createPrismaTenancyExtension(tenancyService)');
  }
  lines.push('// );');

  return lines.join('\n');
}
