import {
  assertValidPostgresSettingKey,
  serializeTypeScriptString,
  serializeTypeScriptStringArray,
} from '../../postgres-safety';
import { DEFAULT_DB_SETTING_KEY } from '../../tenancy.constants';

export interface ModuleSetupOptions {
  extractorType: string;
  dbSettingKey: string;
  autoInjectTenantId: boolean;
  sharedModels: string[];
  tenantFormat?: string;
  customRegex?: string;
  /** Logical Prisma field name used by auto-injection. */
  tenantIdField?: string;
}

export function generateModuleSetup(options: ModuleSetupOptions): string {
  assertValidPostgresSettingKey(options.dbSettingKey);

  // Determine which extractor class (if any) needs to be imported
  const extractorImportMap: Record<string, string> = {
    'Subdomain (tenant1.app.com)': 'SubdomainTenantExtractor',
    'JWT Claim': 'JwtClaimTenantExtractor',
    'Path Parameter': 'PathTenantExtractor',
  };
  const extractorClass = extractorImportMap[options.extractorType];

  // Include the Prisma extension so tenant-scoped model queries set their RLS context.
  const hasExtensionOptions =
    options.autoInjectTenantId ||
    options.sharedModels.length > 0;

  const lines: string[] = [
    '// Generated by @nestarc/tenancy CLI',
    '// Add to your AppModule imports array.',
    '',
  ];

  // Build the import from @nestarc/tenancy
  const namedImports: string[] = ['TenancyModule'];
  if (extractorClass) {
    namedImports.push(extractorClass);
  }
  if (options.extractorType === 'Composite') {
    if (!namedImports.includes('CompositeTenantExtractor')) {
      namedImports.push('CompositeTenantExtractor');
      namedImports.push('HeaderTenantExtractor');
    }
  }
  lines.push(`import { ${namedImports.join(', ')} } from '@nestarc/tenancy';`);
  lines.push('');

  lines.push('// In your @Module({ imports: [...] })', 'TenancyModule.forRoot({');

  switch (options.extractorType) {
    case 'Subdomain (tenant1.app.com)':
      lines.push('  tenantExtractor: new SubdomainTenantExtractor(),');
      break;
    case 'JWT Claim':
      lines.push("  // WARNING: JWT signature must be verified BEFORE tenancy middleware.");
      lines.push("  // Add express-jwt or similar middleware BEFORE TenancyModule.");
      lines.push(
        "  tenantExtractor: new JwtClaimTenantExtractor({ claimKey: 'tenant_id' }),",
      );
      break;
    case 'Path Parameter':
      lines.push(
        "  tenantExtractor: new PathTenantExtractor({ pattern: '/api/tenants/:tenantId', paramName: 'tenantId' }),",
      );
      break;
    case 'Composite':
      lines.push("  tenantExtractor: new CompositeTenantExtractor([");
      lines.push("    new HeaderTenantExtractor('X-Tenant-Id'),");
      lines.push("    // Add more extractors here");
      lines.push("  ]),");
      break;
    default:
      lines.push("  tenantExtractor: 'X-Tenant-Id',");
  }

  if (options.tenantFormat === 'Custom' && options.customRegex) {
    // Use new RegExp() instead of /.../ literal to safely handle regex with '/'
    lines.push(
      `  validateTenantId: (id) => new RegExp(${serializeTypeScriptString(options.customRegex)}).test(id),`,
    );
  }

  if (options.dbSettingKey !== DEFAULT_DB_SETTING_KEY) {
    lines.push(
      `  dbSettingKey: ${serializeTypeScriptString(options.dbSettingKey)},`,
    );
  }

  lines.push('})');

  lines.push('');
  lines.push('// Prisma extension — required for RLS to work:');
  lines.push("// import { createPrismaTenancyExtension } from '@nestarc/tenancy';");
  lines.push('// Prisma 7: create basePrisma with the adapter required by your database.');
  lines.push('// const prisma = basePrisma.$extends(');
  if (hasExtensionOptions) {
    lines.push('//   createPrismaTenancyExtension(tenancyService, {');
    if (options.autoInjectTenantId) {
      lines.push('//     autoInjectTenantId: true,');
      if (options.tenantIdField && options.tenantIdField !== 'tenant_id') {
        lines.push(
          `//     tenantIdField: ${serializeTypeScriptString(options.tenantIdField)},`,
        );
      }
    }
    if (options.sharedModels.length > 0) {
      lines.push(
        `//     sharedModels: ${serializeTypeScriptStringArray(options.sharedModels)},`,
      );
    }
    lines.push('//   })');
  } else {
    lines.push('//   createPrismaTenancyExtension(tenancyService)');
  }
  lines.push('// );');

  return lines.join('\n');
}
