import { ParsedModel } from '../prisma-schema-parser';

export interface SetupSqlOptions {
  models: ParsedModel[];
  dbSettingKey: string;
  sharedModels: string[];
  tenantIdField: string;
}

function qualifiedTableName(model: ParsedModel): string {
  if (model.schemaName) {
    return `"${model.schemaName}"."${model.tableName}"`;
  }
  return `"${model.tableName}"`;
}

export function generateSetupSql(options: SetupSqlOptions): string {
  const { models, dbSettingKey, sharedModels, tenantIdField } = options;
  const sharedSet = new Set(sharedModels);

  // Collect unique schemas for GRANT USAGE statements
  const schemas = new Set<string>(['public']);
  for (const model of models) {
    schemas.add(model.schemaName ?? 'public');
  }

  const lines: string[] = [
    '-- Generated by @nestarc/tenancy CLI',
    '-- Review and customize before running against your database.',
    "-- IMPORTANT: This script assumes all non-shared models have a 'tenant_id' column.",
    '-- Remove or modify policies for models that don\'t use tenant isolation.',
    '',
    '-- Create a non-superuser role for the application',
    'DO $$',
    'BEGIN',
    "  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_user') THEN",
    "    CREATE ROLE app_user LOGIN PASSWORD 'changeme';",
    '  END IF;',
    'END',
    '$$;',
    '',
    '-- GRANT CONNECT ON DATABASE your_database TO app_user;',
  ];

  // Grant schema usage for each unique schema
  for (const schema of schemas) {
    lines.push(`GRANT USAGE ON SCHEMA "${schema}" TO app_user;`);
  }
  lines.push('');

  for (const model of models) {
    const tableName = qualifiedTableName(model);
    const schemaForSeq = model.schemaName ?? 'public';

    if (sharedSet.has(model.modelName)) {
      lines.push(`-- ${model.modelName} (shared model)`);
      lines.push(
        `GRANT SELECT, INSERT, UPDATE, DELETE ON ${tableName} TO app_user;`,
      );
      lines.push('-- Also grant sequence permissions if using SERIAL/autoincrement columns:');
      lines.push(`-- GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA "${schemaForSeq}" TO app_user;`);
      lines.push('');
      continue;
    }

    // Include schema in policy name to avoid cross-schema collisions
    const schemaPrefix = model.schemaName ? `${model.schemaName}_` : '';
    const safeName = `${schemaPrefix}${model.tableName}`.replace(/[^a-zA-Z0-9_]/g, '_');
    lines.push(`-- ${model.modelName}`);
    lines.push(`ALTER TABLE ${tableName} ENABLE ROW LEVEL SECURITY;`);
    lines.push(`ALTER TABLE ${tableName} FORCE ROW LEVEL SECURITY;`);
    lines.push(
      `CREATE POLICY tenant_isolation_${safeName} ON ${tableName}`,
    );
    lines.push(
      `  USING (${tenantIdField} = current_setting('${dbSettingKey}', true)::text);`,
    );
    lines.push(
      `CREATE POLICY tenant_insert_${safeName} ON ${tableName}`,
    );
    lines.push(
      `  FOR INSERT WITH CHECK (${tenantIdField} = current_setting('${dbSettingKey}', true)::text);`,
    );
    lines.push(
      `GRANT SELECT, INSERT, UPDATE, DELETE ON ${tableName} TO app_user;`,
    );
    lines.push('-- Also grant sequence permissions if using SERIAL/autoincrement columns:');
    lines.push(`-- GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA "${schemaForSeq}" TO app_user;`);
    lines.push('');
  }

  // General sequence grant for each schema
  lines.push('-- Grant sequence permissions for all sequences:');
  for (const schema of schemas) {
    lines.push(`GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA "${schema}" TO app_user;`);
  }

  return lines.join('\n');
}
