import { ParsedModel } from '../prisma-schema-parser';

export interface SetupSqlOptions {
  models: ParsedModel[];
  dbSettingKey: string;
  sharedModels: string[];
  tenantIdField: string;
}

export function generateSetupSql(options: SetupSqlOptions): string {
  const { models, dbSettingKey, sharedModels, tenantIdField } = options;
  const sharedSet = new Set(sharedModels);

  const lines: string[] = [
    '-- Generated by @nestarc/tenancy CLI',
    '-- Review and customize before running against your database.',
    "-- IMPORTANT: This script assumes all non-shared models have a 'tenant_id' column.",
    '-- Remove or modify policies for models that don\'t use tenant isolation.',
    '',
    '-- Create a non-superuser role for the application',
    'DO $$',
    'BEGIN',
    "  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_user') THEN",
    "    CREATE ROLE app_user LOGIN PASSWORD 'changeme';",
    '  END IF;',
    'END',
    '$$;',
    '',
    '-- GRANT CONNECT ON DATABASE your_database TO app_user;',
    'GRANT USAGE ON SCHEMA public TO app_user;',
    '',
  ];

  for (const model of models) {
    if (sharedSet.has(model.modelName)) {
      lines.push(`-- ${model.modelName} (shared model)`);
      lines.push(
        `GRANT SELECT, INSERT, UPDATE, DELETE ON "${model.tableName}" TO app_user;`,
      );
      lines.push('-- Also grant sequence permissions if using SERIAL/autoincrement columns:');
      lines.push(`-- GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_user;`);
      lines.push('');
      continue;
    }

    const safeName = model.tableName.replace(/[^a-zA-Z0-9_]/g, '_');
    lines.push(`-- ${model.modelName}`);
    lines.push(`ALTER TABLE "${model.tableName}" ENABLE ROW LEVEL SECURITY;`);
    lines.push(`ALTER TABLE "${model.tableName}" FORCE ROW LEVEL SECURITY;`);
    lines.push(
      `CREATE POLICY tenant_isolation_${safeName} ON "${model.tableName}"`,
    );
    lines.push(
      `  USING (${tenantIdField} = current_setting('${dbSettingKey}', true)::text);`,
    );
    lines.push(
      `CREATE POLICY tenant_insert_${safeName} ON "${model.tableName}"`,
    );
    lines.push(
      `  FOR INSERT WITH CHECK (${tenantIdField} = current_setting('${dbSettingKey}', true)::text);`,
    );
    lines.push(
      `GRANT SELECT, INSERT, UPDATE, DELETE ON "${model.tableName}" TO app_user;`,
    );
    lines.push('-- Also grant sequence permissions if using SERIAL/autoincrement columns:');
    lines.push(`-- GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_user;`);
    lines.push('');
  }

  // General sequence grant for all sequences in the schema
  lines.push('-- Grant sequence permissions for all sequences (SERIAL/autoincrement columns):');
  lines.push('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_user;');

  return lines.join('\n');
}
