import { generateSetupSql } from '../../src/cli/templates/setup-sql';
import { generateModuleSetup } from '../../src/cli/templates/module-setup';

describe('generateSetupSql', () => {
  const baseOptions = {
    models: [],
    dbSettingKey: 'app.current_tenant',
    sharedModels: [],
    tenantIdField: 'tenant_id',
  };

  it('should include standard header and role creation', () => {
    const sql = generateSetupSql(baseOptions);
    expect(sql).toContain('-- Generated by @nestarc/tenancy CLI');
    expect(sql).toContain('CREATE ROLE app_user');
    expect(sql).toContain('GRANT USAGE ON SCHEMA "public" TO app_user;');
  });

  it('should include tenant_id warning comment in header', () => {
    const sql = generateSetupSql(baseOptions);
    expect(sql).toContain("-- IMPORTANT: This script assumes all non-shared models have a 'tenant_id' column.");
    expect(sql).toContain("-- Remove or modify policies for models that don't use tenant isolation.");
  });

  it('should include general sequence grant at the end', () => {
    const sql = generateSetupSql(baseOptions);
    expect(sql).toContain('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA "public" TO app_user;');
  });

  it('should generate RLS policies for non-shared models', () => {
    const options = {
      ...baseOptions,
      models: [{ modelName: 'User', tableName: 'User' }],
    };
    const sql = generateSetupSql(options);
    expect(sql).toContain('ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;');
    expect(sql).toContain('ALTER TABLE "User" FORCE ROW LEVEL SECURITY;');
    expect(sql).toContain('CREATE POLICY tenant_isolation_User ON "User"');
    expect(sql).toContain("current_setting('app.current_tenant', true)::text");
    expect(sql).toContain('CREATE POLICY tenant_insert_User ON "User"');
    expect(sql).toContain('GRANT SELECT, INSERT, UPDATE, DELETE ON "User" TO app_user;');
  });

  it('should use custom dbSettingKey in policies', () => {
    const options = {
      ...baseOptions,
      dbSettingKey: 'app.tenant',
      models: [{ modelName: 'Post', tableName: 'posts' }],
    };
    const sql = generateSetupSql(options);
    expect(sql).toContain("current_setting('app.tenant', true)::text");
  });

  it('should use mapped tableName in policies', () => {
    const options = {
      ...baseOptions,
      models: [{ modelName: 'User', tableName: 'users' }],
    };
    const sql = generateSetupSql(options);
    expect(sql).toContain('ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;');
    expect(sql).toContain('ALTER TABLE "users" FORCE ROW LEVEL SECURITY;');
    expect(sql).toContain('CREATE POLICY tenant_isolation_users ON "users"');
    expect(sql).not.toContain('"User"');
  });

  it('should generate GRANT without RLS for shared models', () => {
    const options = {
      ...baseOptions,
      models: [{ modelName: 'Country', tableName: 'Country' }],
      sharedModels: ['Country'],
    };
    const sql = generateSetupSql(options);
    expect(sql).toContain('-- Country (shared model)');
    expect(sql).toContain('GRANT SELECT, INSERT, UPDATE, DELETE ON "Country" TO app_user;');
    expect(sql).not.toContain('ENABLE ROW LEVEL SECURITY');
  });

  it('should handle a mix of shared and non-shared models', () => {
    const options = {
      ...baseOptions,
      models: [
        { modelName: 'User', tableName: 'User' },
        { modelName: 'Country', tableName: 'Country' },
      ],
      sharedModels: ['Country'],
    };
    const sql = generateSetupSql(options);
    expect(sql).toContain('ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;');
    expect(sql).toContain('-- Country (shared model)');
    expect(sql).not.toContain('ALTER TABLE "Country" ENABLE ROW LEVEL SECURITY');
  });

  it('should produce valid output for empty models list', () => {
    const sql = generateSetupSql(baseOptions);
    expect(sql).toBeTruthy();
    expect(sql).not.toContain('ENABLE ROW LEVEL SECURITY');
    expect(sql).not.toContain('(shared model)');
  });

  it('should use custom tenantIdField in policy', () => {
    const options = {
      ...baseOptions,
      tenantIdField: 'org_id',
      models: [{ modelName: 'Order', tableName: 'orders' }],
    };
    const sql = generateSetupSql(options);
    expect(sql).toContain('org_id = current_setting');
  });

  it('should sanitize hyphenated table names in policy identifiers', () => {
    const options = {
      ...baseOptions,
      models: [{ modelName: 'AuditLog', tableName: 'audit-logs' }],
    };
    const sql = generateSetupSql(options);
    expect(sql).toContain('ALTER TABLE "audit-logs" ENABLE ROW LEVEL SECURITY;');
    expect(sql).toContain('ALTER TABLE "audit-logs" FORCE ROW LEVEL SECURITY;');
    expect(sql).toContain('CREATE POLICY tenant_isolation_audit_logs ON "audit-logs"');
    expect(sql).toContain('CREATE POLICY tenant_insert_audit_logs ON "audit-logs"');
    expect(sql).not.toContain('tenant_isolation_audit-logs');
    expect(sql).not.toContain('tenant_insert_audit-logs');
  });

  describe('@@schema support', () => {
    it('should generate schema-qualified table names', () => {
      const options = {
        ...baseOptions,
        models: [{ modelName: 'User', tableName: 'users', schemaName: 'auth' }],
      };
      const sql = generateSetupSql(options);
      expect(sql).toContain('ALTER TABLE "auth"."users" ENABLE ROW LEVEL SECURITY;');
      expect(sql).toContain('ALTER TABLE "auth"."users" FORCE ROW LEVEL SECURITY;');
      expect(sql).toContain('CREATE POLICY tenant_isolation_auth_users ON "auth"."users"');
      expect(sql).toContain('CREATE POLICY tenant_insert_auth_users ON "auth"."users"');
      expect(sql).toContain('GRANT SELECT, INSERT, UPDATE, DELETE ON "auth"."users" TO app_user;');
    });

    it('should include GRANT USAGE for non-public schemas', () => {
      const options = {
        ...baseOptions,
        models: [{ modelName: 'User', tableName: 'users', schemaName: 'auth' }],
      };
      const sql = generateSetupSql(options);
      expect(sql).toContain('GRANT USAGE ON SCHEMA "auth" TO app_user;');
      expect(sql).toContain('GRANT USAGE ON SCHEMA "public" TO app_user;');
    });

    it('should include sequence grants for each schema', () => {
      const options = {
        ...baseOptions,
        models: [
          { modelName: 'User', tableName: 'users', schemaName: 'auth' },
          { modelName: 'Order', tableName: 'orders' },
        ],
      };
      const sql = generateSetupSql(options);
      expect(sql).toContain('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA "auth" TO app_user;');
      expect(sql).toContain('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA "public" TO app_user;');
    });

    it('should handle mix of schema and non-schema models', () => {
      const options = {
        ...baseOptions,
        models: [
          { modelName: 'User', tableName: 'users', schemaName: 'auth' },
          { modelName: 'Post', tableName: 'posts' },
        ],
      };
      const sql = generateSetupSql(options);
      expect(sql).toContain('ALTER TABLE "auth"."users" ENABLE ROW LEVEL SECURITY;');
      expect(sql).toContain('ALTER TABLE "posts" ENABLE ROW LEVEL SECURITY;');
      expect(sql).not.toContain('"auth"."posts"');
    });

    it('should include schema prefix in policy names to avoid collisions', () => {
      const options = {
        ...baseOptions,
        models: [
          { modelName: 'User', tableName: 'users', schemaName: 'auth' },
          { modelName: 'AdminUser', tableName: 'users', schemaName: 'admin' },
        ],
      };
      const sql = generateSetupSql(options);
      expect(sql).toContain('tenant_isolation_auth_users');
      expect(sql).toContain('tenant_isolation_admin_users');
    });

    it('should handle shared models with schema', () => {
      const options = {
        ...baseOptions,
        models: [{ modelName: 'Country', tableName: 'countries', schemaName: 'reference' }],
        sharedModels: ['Country'],
      };
      const sql = generateSetupSql(options);
      expect(sql).toContain('-- Country (shared model)');
      expect(sql).toContain('GRANT SELECT, INSERT, UPDATE, DELETE ON "reference"."countries" TO app_user;');
      expect(sql).not.toContain('ENABLE ROW LEVEL SECURITY');
    });
  });
});

describe('generateModuleSetup', () => {
  const baseOptions = {
    extractorType: 'Header (X-Tenant-Id)',
    dbSettingKey: 'app.current_tenant',
    autoInjectTenantId: false,
    sharedModels: [],
  };

  it('should include standard header comment', () => {
    const result = generateModuleSetup(baseOptions);
    expect(result).toContain('// Generated by @nestarc/tenancy CLI');
    expect(result).toContain('TenancyModule.forRoot({');
  });

  it('should use Header extractor (default) when type is Header (X-Tenant-Id)', () => {
    const result = generateModuleSetup(baseOptions);
    expect(result).toContain("tenantExtractor: 'X-Tenant-Id',");
    expect(result).toContain("import { TenancyModule, createPrismaTenancyExtension } from '@nestarc/tenancy';");
  });

  it('should use SubdomainTenantExtractor for Subdomain type', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      extractorType: 'Subdomain (tenant1.app.com)',
    });
    expect(result).toContain('new SubdomainTenantExtractor()');
    expect(result).toContain('SubdomainTenantExtractor');
    expect(result).toContain('SubdomainTenantExtractor');
    expect(result).toContain('createPrismaTenancyExtension');
  });

  it('should use JwtClaimTenantExtractor for JWT Claim type', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      extractorType: 'JWT Claim',
    });
    expect(result).toContain("new JwtClaimTenantExtractor({ claimKey: 'tenant_id' })");
    expect(result).toContain('JwtClaimTenantExtractor');
    expect(result).toContain('JwtClaimTenantExtractor');
    expect(result).toContain('createPrismaTenancyExtension');
  });

  it('should use PathTenantExtractor for Path Parameter type', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      extractorType: 'Path Parameter',
    });
    expect(result).toContain("new PathTenantExtractor({ pattern: '/api/tenants/:tenantId', paramName: 'tenantId' })");
    expect(result).toContain('PathTenantExtractor');
    expect(result).toContain('PathTenantExtractor');
    expect(result).toContain('createPrismaTenancyExtension');
  });

  it('should use Composite scaffold for Composite type', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      extractorType: 'Composite',
    });
    expect(result).toContain('new CompositeTenantExtractor([');
    expect(result).toContain("new HeaderTenantExtractor('X-Tenant-Id'),");
    expect(result).toContain('// Add more extractors here');
    expect(result).toContain('CompositeTenantExtractor');
    expect(result).toContain('HeaderTenantExtractor');
    expect(result).toContain('createPrismaTenancyExtension');
  });

  it('should fall through to default (header string) for unknown extractor type', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      extractorType: 'Unknown',
    });
    expect(result).toContain("tenantExtractor: 'X-Tenant-Id',");
  });

  it('should NOT include dbSettingKey when it equals the default app.current_tenant', () => {
    const result = generateModuleSetup(baseOptions);
    expect(result).not.toContain('dbSettingKey:');
  });

  it('should include dbSettingKey when it differs from the default', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      dbSettingKey: 'app.tenant',
    });
    expect(result).toContain("dbSettingKey: 'app.tenant',");
  });

  it('should include extension options block when only dbSettingKey is custom', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      dbSettingKey: 'app.tenant',
    });
    expect(result).toContain('createPrismaTenancyExtension(tenancyService, {');
    expect(result).toContain("dbSettingKey: 'app.tenant',");
  });

  it('should always include Prisma extension block', () => {
    const result = generateModuleSetup(baseOptions);
    expect(result).toContain('createPrismaTenancyExtension(tenancyService)');
    expect(result).toContain('// Prisma extension — required for RLS to work:');
  });

  it('should include options in extension block when autoInjectTenantId is true', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      autoInjectTenantId: true,
    });
    expect(result).toContain('createPrismaTenancyExtension(tenancyService, {');
    expect(result).toContain('autoInjectTenantId: true,');
  });

  it('should include sharedModels in extension block when provided', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      sharedModels: ['Country', 'Currency'],
    });
    expect(result).toContain("sharedModels: ['Country', 'Currency'],");
  });

  it('should include both autoInjectTenantId and sharedModels when both are provided', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      autoInjectTenantId: true,
      sharedModels: ['Country'],
    });
    expect(result).toContain('autoInjectTenantId: true,');
    expect(result).toContain("sharedModels: ['Country'],");
  });

  it('should include validateTenantId when tenantFormat is Custom and customRegex is provided', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      tenantFormat: 'Custom',
      customRegex: '^[a-z0-9-]+$',
    });
    expect(result).toContain("validateTenantId: (id) => new RegExp('^[a-z0-9-]+$').test(id),");
  });

  it('should safely handle customRegex containing forward slashes', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      tenantFormat: 'Custom',
      customRegex: '^acme/.+$',
    });
    expect(result).toContain("validateTenantId: (id) => new RegExp('^acme/.+$').test(id),");
  });

  it('should escape backslashes in customRegex for string context', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      tenantFormat: 'Custom',
      customRegex: '^\\d{3}-\\d{4}$',
    });
    expect(result).toContain("validateTenantId: (id) => new RegExp('^\\\\d{3}-\\\\d{4}$').test(id),");
  });

  it('should NOT include validateTenantId when tenantFormat is UUID', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      tenantFormat: 'UUID',
      customRegex: '^[a-z0-9-]+$',
    });
    expect(result).not.toContain('validateTenantId');
  });

  it('should NOT include validateTenantId when tenantFormat is Custom but customRegex is empty', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      tenantFormat: 'Custom',
      customRegex: '',
    });
    expect(result).not.toContain('validateTenantId');
  });
});
