import { generateSetupSql } from '../../src/cli/templates/setup-sql';
import { generateModuleSetup } from '../../src/cli/templates/module-setup';

describe('generateSetupSql', () => {
  const baseOptions = {
    models: [],
    dbSettingKey: 'app.current_tenant',
    sharedModels: [],
    tenantIdField: 'tenant_id',
  };

  it('should include standard header and role creation', () => {
    const sql = generateSetupSql(baseOptions);
    expect(sql).toContain('-- Generated by @nestarc/tenancy CLI');
    expect(sql).toContain('CREATE ROLE app_user');
    expect(sql).toContain('GRANT USAGE ON SCHEMA public TO app_user;');
  });

  it('should include general sequence grant at the end', () => {
    const sql = generateSetupSql(baseOptions);
    expect(sql).toContain('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_user;');
  });

  it('should generate RLS policies for non-shared models', () => {
    const options = {
      ...baseOptions,
      models: [{ modelName: 'User', tableName: 'User' }],
    };
    const sql = generateSetupSql(options);
    expect(sql).toContain('ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;');
    expect(sql).toContain('CREATE POLICY tenant_isolation_User ON "User"');
    expect(sql).toContain("current_setting('app.current_tenant', true)::text");
    expect(sql).toContain('CREATE POLICY tenant_insert_User ON "User"');
    expect(sql).toContain('GRANT SELECT, INSERT, UPDATE, DELETE ON "User" TO app_user;');
  });

  it('should use custom dbSettingKey in policies', () => {
    const options = {
      ...baseOptions,
      dbSettingKey: 'app.tenant',
      models: [{ modelName: 'Post', tableName: 'posts' }],
    };
    const sql = generateSetupSql(options);
    expect(sql).toContain("current_setting('app.tenant', true)::text");
  });

  it('should use mapped tableName in policies', () => {
    const options = {
      ...baseOptions,
      models: [{ modelName: 'User', tableName: 'users' }],
    };
    const sql = generateSetupSql(options);
    expect(sql).toContain('ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;');
    expect(sql).toContain('CREATE POLICY tenant_isolation_users ON "users"');
    expect(sql).not.toContain('"User"');
  });

  it('should generate GRANT without RLS for shared models', () => {
    const options = {
      ...baseOptions,
      models: [{ modelName: 'Country', tableName: 'Country' }],
      sharedModels: ['Country'],
    };
    const sql = generateSetupSql(options);
    expect(sql).toContain('-- Country (shared model)');
    expect(sql).toContain('GRANT SELECT, INSERT, UPDATE, DELETE ON "Country" TO app_user;');
    expect(sql).not.toContain('ENABLE ROW LEVEL SECURITY');
  });

  it('should handle a mix of shared and non-shared models', () => {
    const options = {
      ...baseOptions,
      models: [
        { modelName: 'User', tableName: 'User' },
        { modelName: 'Country', tableName: 'Country' },
      ],
      sharedModels: ['Country'],
    };
    const sql = generateSetupSql(options);
    expect(sql).toContain('ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;');
    expect(sql).toContain('-- Country (shared model)');
    expect(sql).not.toContain('ALTER TABLE "Country" ENABLE ROW LEVEL SECURITY');
  });

  it('should produce valid output for empty models list', () => {
    const sql = generateSetupSql(baseOptions);
    expect(sql).toBeTruthy();
    expect(sql).not.toContain('ENABLE ROW LEVEL SECURITY');
    expect(sql).not.toContain('shared model');
  });

  it('should use custom tenantIdField in policy', () => {
    const options = {
      ...baseOptions,
      tenantIdField: 'org_id',
      models: [{ modelName: 'Order', tableName: 'orders' }],
    };
    const sql = generateSetupSql(options);
    expect(sql).toContain('org_id = current_setting');
  });
});

describe('generateModuleSetup', () => {
  const baseOptions = {
    extractorType: 'Header (X-Tenant-Id)',
    dbSettingKey: 'app.current_tenant',
    autoInjectTenantId: false,
    sharedModels: [],
  };

  it('should include standard header comment', () => {
    const result = generateModuleSetup(baseOptions);
    expect(result).toContain('// Generated by @nestarc/tenancy CLI');
    expect(result).toContain('TenancyModule.forRoot({');
  });

  it('should use Header extractor (default) when type is Header (X-Tenant-Id)', () => {
    const result = generateModuleSetup(baseOptions);
    expect(result).toContain("tenantExtractor: 'X-Tenant-Id',");
    expect(result).toContain("import { TenancyModule } from '@nestarc/tenancy';");
  });

  it('should use SubdomainTenantExtractor for Subdomain type', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      extractorType: 'Subdomain (tenant1.app.com)',
    });
    expect(result).toContain('new SubdomainTenantExtractor()');
    expect(result).toContain('SubdomainTenantExtractor');
    expect(result).toContain("import { TenancyModule, SubdomainTenantExtractor } from '@nestarc/tenancy';");
  });

  it('should use JwtClaimTenantExtractor for JWT Claim type', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      extractorType: 'JWT Claim',
    });
    expect(result).toContain("new JwtClaimTenantExtractor({ claimKey: 'tenant_id' })");
    expect(result).toContain('JwtClaimTenantExtractor');
    expect(result).toContain("import { TenancyModule, JwtClaimTenantExtractor } from '@nestarc/tenancy';");
  });

  it('should use PathTenantExtractor for Path Parameter type', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      extractorType: 'Path Parameter',
    });
    expect(result).toContain("new PathTenantExtractor({ pattern: '/api/tenants/:tenantId' })");
    expect(result).toContain('PathTenantExtractor');
    expect(result).toContain("import { TenancyModule, PathTenantExtractor } from '@nestarc/tenancy';");
  });

  it('should use Composite placeholder for Composite type', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      extractorType: 'Composite',
    });
    expect(result).toContain('/* configure your CompositeExtractor here */');
    // Composite is not in extractorImportMap so no extra import
    expect(result).toContain("import { TenancyModule } from '@nestarc/tenancy';");
  });

  it('should fall through to default (header string) for unknown extractor type', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      extractorType: 'Unknown',
    });
    expect(result).toContain("tenantExtractor: 'X-Tenant-Id',");
  });

  it('should NOT include dbSettingKey when it equals the default app.current_tenant', () => {
    const result = generateModuleSetup(baseOptions);
    expect(result).not.toContain('dbSettingKey:');
  });

  it('should include dbSettingKey when it differs from the default', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      dbSettingKey: 'app.tenant',
    });
    expect(result).toContain("dbSettingKey: 'app.tenant',");
  });

  it('should include createPrismaTenancyExtension block when autoInjectTenantId is true', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      autoInjectTenantId: true,
    });
    expect(result).toContain('createPrismaTenancyExtension(tenancyService, {');
    expect(result).toContain('autoInjectTenantId: true,');
    expect(result).toContain('createPrismaTenancyExtension');
    expect(result).toContain("import { TenancyModule, createPrismaTenancyExtension } from '@nestarc/tenancy';");
  });

  it('should include sharedModels in createPrismaTenancyExtension block when provided', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      sharedModels: ['Country', 'Currency'],
    });
    expect(result).toContain("sharedModels: ['Country', 'Currency'],");
    expect(result).toContain('createPrismaTenancyExtension');
    expect(result).toContain("import { TenancyModule, createPrismaTenancyExtension } from '@nestarc/tenancy';");
  });

  it('should include both autoInjectTenantId and sharedModels when both are provided', () => {
    const result = generateModuleSetup({
      ...baseOptions,
      autoInjectTenantId: true,
      sharedModels: ['Country'],
    });
    expect(result).toContain('autoInjectTenantId: true,');
    expect(result).toContain("sharedModels: ['Country'],");
  });

  it('should NOT include createPrismaTenancyExtension block when neither flag is set', () => {
    const result = generateModuleSetup(baseOptions);
    expect(result).not.toContain('createPrismaTenancyExtension');
  });
});
